plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

Style/Documentation:
  Enabled: false

ThreadSafety/DirChdir:
  Enabled: false

RSpec/ExampleLength:
  Max: 10
