- name: rubocop
  url: https://github.com/rubocop/rubocop.git
  branch: master
  type: core
- name: rubocop-ast
  url: https://github.com/rubocop/rubocop-ast.git
  branch: master
  type: core
- name: rubocop-rake
  url: https://github.com/rubocop/rubocop-rake.git
  branch: master
  type: plugin
  post_install_script: cd $(bundle info --path rubocop-ast) && bundle install && bundle exec rake generate
- name: rubocop-rspec
  url: https://github.com/rubocop/rubocop-rspec.git
  branch: master
  type: plugin
- name: rubocop-thread_safety
  url: https://github.com/rubocop/rubocop-thread_safety.git
  branch: master
  type: plugin
- name: rubocop-performance
  url: https://github.com/rubocop/rubocop-performance.git
  branch: master
  type: plugin
- name: rubocop-minitest
  url: https://github.com/rubocop/rubocop-minitest.git
  branch: master
  type: plugin
- name: rubocop-sequel
  url: https://github.com/rubocop/rubocop-sequel.git
  branch: master
  type: plugin
- name: rubocop-capybara
  url: https://github.com/rubocop/rubocop-capybara.git
  branch: main
  type: plugin
- name: rubocop-factory_bot
  url: https://github.com/rubocop/rubocop-factory_bot.git
  branch: master
  type: plugin
- name: rubocop-rspec_rails
  url: https://github.com/rubocop/rubocop-rspec_rails.git
  branch: master
  type: plugin
- name: rubocop-packaging
  url: https://github.com/utkarsh2102/rubocop-packaging.git
  type: plugin
  branch: master
- name: rubocop-rails
  url: https://github.com/rubocop/rubocop-rails.git
  branch: master
  type: plugin
